import { Season9TeamComp } from "../type";

export const season9ChampionList = [
  { name: "Aatrox", cost: 5 },
  { name: "Ahri", cost: 5 },
  { name: "Akshan", cost: 3 },
  { name: "Aphelios", cost: 4 },
  { name: "Ashe", cost: 2 },
  { name: "Azir", cost: 4 },
  { name: "Belveth", cost: 5 },
  { name: "Cassiopeia", cost: 1 },
  { name: "Chogath", cost: 1 },
  { name: "Darius", cost: 3 },
  { name: "Ekko", cost: 3 },
  { name: "Galio", cost: 2 },
  { name: "Garen", cost: 3 },
  { name: "Gwen", cost: 4 },
  { name: "Heimerdinger", cost: 5 },
  { name: "Irelia", cost: 1 },
  { name: "JarvanIV", cost: 4 },
  { name: "Jayce", cost: 3 },
  { name: "Jhin", cost: 1 },
  { name: "Jinx", cost: 2 },
  { name: "Kaisa", cost: 4 },
  { name: "Kalista", cost: 3 },
  { name: "Karma", cost: 3 },
  { name: "Kassadin", cost: 2 },
  { name: "Katarina", cost: 3 },
  { name: "Kayle", cost: 1 },
  { name: "Kled", cost: 2 },
  { name: "KSante", cost: 5 },
  { name: "Lissandra", cost: 3 },
  { name: "Lux", cost: 4 },
  { name: "Malzahar", cost: 1 },
  { name: "Maokai", cost: 1 },
  { name: "Nasus", cost: 4 },
  { name: "Orianna", cost: 1 },
  { name: "Poppy", cost: 1 },
  { name: "Renekton", cost: 1 },
  { name: "RekSai", cost: 3 },
  { name: "Ryze", cost: 5 },
  { name: "Samira", cost: 1 },
  { name: "Sejuani", cost: 4 },
  { name: "Senna", cost: 5 },
  { name: "Sett", cost: 2 },
  { name: "Shen", cost: 4 },
  { name: "Sion", cost: 5 },
  { name: "Sona", cost: 3 },
  { name: "Soraka", cost: 2 },
  { name: "Swain", cost: 2 },
  { name: "Taliyah", cost: 2 },
  { name: "Taric", cost: 3 },
  { name: "Teemo", cost: 2 },
  { name: "Tristana", cost: 1 },
  { name: "Urgot", cost: 4 },
  { name: "Velkoz", cost: 3 },
  { name: "Viego", cost: 1 },
  { name: "Vi", cost: 2 },
  { name: "Warwick", cost: 2 },
  { name: "Yasuo", cost: 4 },
  { name: "Zed", cost: 2 },
  { name: "Zeri", cost: 4 },
];

export interface TFTLegendMap {
  [key: number]: string;
}

export const TFTLegendMap: TFTLegendMap = {
  27: "AurelionSol",
  28: "Bard",
  23: "Caitlyn",
  19: "Draven",
  18: "Ezreal",
  26: "LeeSin",
  25: "MasterYi",
  22: "Ornn",
  24: "Pengu",
  16: "TahmKench",
  20: "TwistedFate",
  21: "Urf",
  15: "Veigar",
  17: "Vladimir",
};

export const season9EarlyGameTeamCompData: Season9TeamComp[] = [
  {
    name: "1",
    champions: [
      { name: "Irelia", item: [] },
      { name: "Cassiopeia", item: [] },
      { name: "Samira", item: [] },
      {
        name: "Swain",
        item: [],
      },
    ],
  },
  {
    name: "2",
    champions: [
      { name: "Irelia", item: [] },
      { name: "Jhin", item: [] },
      { name: "Sett", item: [] },
      {
        name: "Warwick",
        item: [],
      },
    ],
  },
  {
    name: "3",
    champions: [
      { name: "Cassiopeia", item: [] },
      { name: "Jhin", item: [] },
      { name: "Renekton", item: [] },
      {
        name: "Akshan",
        item: [],
      },
    ],
  },
  {
    name: "4",
    champions: [
      { name: "Chogath", item: [] },
      { name: "Malzahar", item: [] },
      { name: "Kassadin", item: [] },
      {
        name: "Swain",
        item: [],
      },
    ],
  },
  {
    name: "5",
    champions: [
      { name: "Irelia", item: [] },
      { name: "Jhin", item: [] },
      { name: "Samira", item: [] },
      {
        name: "Sett",
        item: [],
      },
    ],
  },
  {
    name: "6",
    champions: [
      { name: "Cassiopeia", item: [] },
      { name: "Irelia", item: [] },
      { name: "Samira", item: [] },
      {
        name: "Katarina",
        item: [],
      },
    ],
  },
  {
    name: "7",
    champions: [
      { name: "Irelia", item: [] },
      { name: "Maokai", item: [] },
      { name: "Poppy", item: [] },
      {
        name: "Kalista",
        item: [],
      },
    ],
  },
  {
    name: "8",
    champions: [
      { name: "Chogath", item: [] },
      { name: "Malzahar", item: [] },
      { name: "Poppy", item: [] },
      {
        name: "Kalista",
        item: [],
      },
    ],
  },
  {
    name: "9",
    champions: [
      { name: "Chogath", item: [] },
      { name: "Malzahar", item: [] },
      { name: "Renekton", item: [] },
      {
        name: "Kassadin",
        item: [],
      },
    ],
  },
  {
    name: "10",
    champions: [
      { name: "Cassiopeia", item: [] },
      { name: "Chogath", item: [] },
      { name: "Renekton", item: [] },
      {
        name: "Taliyah",
        item: [],
      },
    ],
  },
  {
    name: "11",
    champions: [
      { name: "Irelia", item: [] },
      { name: "Samira", item: [] },
      { name: "Viego", item: [] },
      {
        name: "Warwick",
        item: [],
      },
      { name: "Kalista", item: [] },
    ],
  },
  {
    name: "12",
    champions: [
      { name: "Malzahar", item: [] },
      { name: "Orianna", item: [] },
      { name: "Swain", item: [] },
      {
        name: "Taric",
        item: [],
      },
    ],
  },
  {
    name: "13",
    champions: [
      { name: "Irelia", item: [] },
      { name: "Sett", item: [] },
      { name: "Warwick", item: [] },
      {
        name: "Zed",
        item: [],
      },
    ],
  },
  {
    name: "14",
    champions: [
      { name: "Cassiopeia", item: [] },
      { name: "Galio", item: [] },
      { name: "Soraka", item: [] },
      {
        name: "Karma",
        item: [],
      },
    ],
  },
  {
    name: "15",
    champions: [
      { name: "Chogath", item: [] },
      { name: "Jhin", item: [] },
      { name: "Renekton", item: [] },
      {
        name: "Ashe",
        item: [],
      },
    ],
  },
];

// export const season9LateGameTeamCompData: Season9TeamComp[] = [
//   {
//     name: "Challengers",
//     tier: "S",
//     speed: "(Mid Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       { name: "Irelia", item: [] },
//       { name: "Samira", item: [] },
//       { name: "Warwick", item: [] },
//       {
//         name: "Kalista",
//         item: ["GiantSlayer", "GuinsoosRageblade", "StatikkShiv"],
//       },
//       { name: "Kaisa", item: [] },
//       { name: "Shen", item: [] },
//       {
//         name: "Yasuo",
//         item: ["InfinityEdge", "Bloodthirster", "TitansResolve"],
//       },
//       { name: "Aatrox", item: [] },
//     ],
//   },
//   {
//     name: "Warwick Juggernaut",
//     tier: "S",
//     speed: "(Early Game Comp)",
//     date: "July 1st, 2023",
//     augments: [""],
//     win: 0,
//     loss: 0,
//     champions: [
//       { name: "Irelia", item: [] },
//       { name: "Samira", item: [] },
//       {
//         name: "Warwick",
//         item: ["GuinsoosRageblade", "Bloodthirster", "Quicksilver"],
//       },
//       {
//         name: "Garen",
//         item: [],
//       },
//       { name: "Darius", item: [] },
//       { name: "Kaisa", item: ["ArchangelsStaff", "StatikkShiv"] },
//       {
//         name: "Yasuo",
//         item: ["JuggernautEmblem"],
//       },
//       { name: "Aatrox", item: [] },
//     ],
//   },
//   {
//     name: "4 Challengers + 6 Ionia",
//     tier: "S",
//     speed: "(Mid Game Comp)",
//     date: "June 15th, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       { name: "Irelia", item: [] },
//       { name: "Sett", item: [] },
//       { name: "Warwick", item: [] },
//       { name: "Karma", item: [] },
//       { name: "Kaisa", item: [] },
//       {
//         name: "Shen",
//         item: ["Redemption", "SunfireCape", "WarmogsArmor"],
//       },
//       {
//         name: "Yasuo",
//         item: ["InfinityEdge", "Bloodthirster", "TitansResolve"],
//       },
//       { name: "Ahri", item: [] },
//     ],
//   },
//   {
//     name: "Challengers + Shadow",
//     tier: "S",
//     speed: "(Mid Game Comp)",
//     date: "July 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       { name: "Irelia", item: [] },
//       { name: "Samira", item: [] },
//       { name: "Warwick", item: [] },
//       { name: "Kalista", item: [] },
//       { name: "Kaisa", item: [] },
//       { name: "Shen", item: [] },
//       {
//         name: "Yasuo",
//         item: ["InfinityEdge", "Bloodthirster", "TitansResolve"],
//       },
//       {
//         name: "Gwen",
//         item: ["HextechGunblade", "BlueBuff", "JeweledGauntlet"],
//       },
//     ],
//   },
//   {
//     name: "Shadow Yasuo",
//     tier: "S",
//     speed: "(Mid Game Comp)",
//     date: "July 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       { name: "Irelia", item: [] },
//       { name: "Maokai", item: [] },
//       {
//         name: "Kalista",
//         item: ["JeweledGauntlet", "GuinsoosRageblade", "ArchangelsStaff"],
//       },
//       {
//         name: "Gwen",
//         item: [],
//       },
//       { name: "Kaisa", item: ["ZekesHerald", "ZekesHerald"] },
//       { name: "Shen", item: [] },
//       {
//         name: "Yasuo",
//         item: ["Bloodthirster", "TitansResolve", "ShadowisleEmblem"],
//       },
//       {
//         name: "Ryze",
//         item: [],
//       },
//     ],
//   },
//   {
//     name: "Void",
//     tier: "S",
//     speed: "(Late Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       { name: "Chogath", item: [] },
//       {
//         name: "Malzahar",
//         item: [],
//       },
//       {
//         name: "Kassadin",
//         item: [],
//       },
//       { name: "RekSai", item: [] },
//       { name: "Velkoz", item: [] },
//       {
//         name: "Kaisa",
//         item: ["GuinsoosRageblade", "JeweledGauntlet", "HextechGunblade"],
//       },
//       {
//         name: "Yasuo",
//         item: ["VoidEmblem"],
//       },
//       {
//         name: "Belveth",
//         item: ["Bloodthirster", "InfinityEdge", "TitansResolve"],
//       },
//     ],
//   },
//   {
//     name: "6 Ionia",
//     tier: "A",
//     speed: "(Late Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 1,
//     loss: 1,
//     champions: [
//       { name: "Jhin", item: [] },
//       { name: "Irelia", item: [] },
//       { name: "Sett", item: [] },
//       { name: "Taric", item: [] },
//       {
//         name: "Aphelios",
//         item: ["GuinsoosRageblade", "LastWhisper"],
//       },
//       { name: "Shen", item: [] },
//       {
//         name: "Yasuo",
//         item: ["Bloodthirster", "EdgeofNight", "TitansResolve"],
//       },
//       {
//         name: "Ahri",
//         item: ["ArchangelsStaff", "BlueBuff"],
//       },
//     ],
//   },
//   {
//     name: "Invokers",
//     tier: "B",
//     speed: "(Mid Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 2,
//     loss: 2,
//     champions: [
//       { name: "Galio", item: [] },
//       { name: "Soraka", item: [] },
//       {
//         name: "Lissandra",
//         item: [],
//       },
//       { name: "Taric", item: ["Redemption", "IonicSpark", "WarmogsArmor"] },
//       {
//         name: "Karma",
//         item: ["HextechGunblade", "JeweledGauntlet", "GiantSlayer"],
//       },
//       { name: "Shen", item: [] },
//       { name: "Ryze", item: [] },
//       { name: "Ahri", item: [] },
//     ],
//   },
//   {
//     name: "DeadEye",
//     tier: "S",
//     speed: "(Late Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 2,
//     loss: 0,
//     champions: [
//       { name: "Ashe", item: [] },
//       { name: "Akshan", item: [] },
//       {
//         name: "Lissandra",
//         item: [],
//       },
//       { name: "Taric", item: [] },
//       {
//         name: "Sejuani",
//         item: ["Redemption", "SunfireCape", "WarmogsArmor"],
//       },
//       { name: "Shen", item: [] },
//       {
//         name: "Aphelios",
//         item: ["GiantSlayer", "GuinsoosRageblade", "InfinityEdge"],
//       },
//       { name: "Urgot", item: [] },
//     ],
//   },
//   {
//     name: "Zeri",
//     tier: "S",
//     speed: "(Late Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 2,
//     champions: [
//       { name: "Jinx", item: [] },
//       { name: "Jayce", item: [] },
//       {
//         name: "Lissandra",
//         item: [],
//       },
//       {
//         name: "Zeri",
//         item: ["GiantSlayer", "GuinsoosRageblade", "InfinityEdge"],
//       },
//       {
//         name: "Sejuani",
//         item: ["Redemption", "SunfireCape", "WarmogsArmor"],
//       },
//       { name: "Shen", item: [] },
//       { name: "Senna", item: [] },
//       { name: "Sion", item: [] },
//     ],
//   },
//   {
//     name: "Yordle Gunner",
//     tier: "S",
//     speed: "(Early Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 3,
//     loss: 0,
//     champions: [
//       { name: "Poppy", item: [] },
//       {
//         name: "Tristana",
//         item: ["GiantSlayer", "HextechGunblade", "LastWhisper"],
//       },
//       {
//         name: "Maokai",
//         item: ["Redemption", "SunfireCape", "WarmogsArmor"],
//       },
//       { name: "Viego", item: [] },
//       { name: "Jinx", item: [] },
//       { name: "Jayce", item: [] },
//       { name: "Zeri", item: [] },
//       {
//         name: "Heimerdinger",
//         item: [],
//       },
//     ],
//   },
//   {
//     name: "5 Yordles",
//     tier: "A",
//     speed: "(Early Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 2,
//     loss: 0,
//     champions: [
//       {
//         name: "Poppy",
//         item: ["Redemption", "SunfireCape", "WarmogsArmor"],
//       },
//       {
//         name: "Tristana",
//         item: ["GiantSlayer", "HextechGunblade", "LastWhisper"],
//       },
//       { name: "Kled", item: [] },
//       { name: "Teemo", item: [] },
//       { name: "Sona", item: [] },
//       { name: "Jarvan", item: [] },
//       { name: "Shen", item: [] },
//       {
//         name: "Heimerdinger",
//         item: [],
//       },
//     ],
//   },
//   {
//     name: "Shadow Isle",
//     tier: "A",
//     speed: "(Early Game Comp)",
//     date: "June 15th, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       {
//         name: "Maokai",
//         item: ["Redemption", "SunfireCape", "WarmogsArmor"],
//       },
//       {
//         name: "Viego",
//         item: ["InfinityEdge", "Bloodthirster", "TitansResolve"],
//       },
//       { name: "Zed", item: [] },
//       { name: "Ekko", item: [] },
//       { name: "Kalista", item: [] },
//       {
//         name: "Katarina",
//         item: [],
//       },
//       { name: "Gwen", item: [] },
//     ],
//   },
//   {
//     name: "Shadow Isle 2",
//     tier: "A",
//     speed: "(Late Game Comp)",
//     date: "July 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       { name: "Maokai", item: [] },
//       { name: "Viego", item: [] },
//       { name: "Zed", item: [] },
//       { name: "Kled", item: [] },
//       {
//         name: "Gwen",
//         item: ["HextechGunblade", "BlueBuff", "JeweledGauntlet"],
//       },
//       {
//         name: "Aatrox",
//         item: ["Redemption", "SunfireCape", "WarmogsArmor"],
//       },
//       { name: "KSante", item: [] },
//       { name: "Senna", item: [] },
//     ],
//   },
//   {
//     name: "Multicaster",
//     tier: "S",
//     speed: "(Early Game Comp)",
//     date: "July 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       {
//         name: "Poppy",
//         item: [],
//       },
//       { name: "Kled", item: [] },
//       { name: "Taliyah", item: [] },
//       {
//         name: "Teemo",
//         item: ["JeweledGauntlet", "HextechGunblade", "BlueBuff"],
//       },
//       { name: "Swain", item: ["Redemption", "SunfireCape", "WarmogsArmor"] },
//       { name: "Galio", item: [] },
//       { name: "Velkoz", item: [] },
//       { name: "Sona", item: [] },
//     ],
//   },
//   {
//     name: "Strategist",
//     tier: "B",
//     speed: "(Mid Game Comp)",
//     date: "June 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       { name: "Taliyah", item: [] },
//       { name: "Teemo", item: [] },
//       { name: "Swain", item: [] },
//       { name: "Garen", item: [] },
//       {
//         name: "Azir",
//         item: ["GuinsoosRageblade", "StatikkShiv", "JeweledGauntlet"],
//       },
//       { name: "Jarvan", item: [] },
//       {
//         name: "Nasus",
//         item: ["Redemption", "SunfireCape", "WarmogsArmor"],
//       },
//       { name: "Lux", item: [] },
//     ],
//   },
//   {
//     name: "Shurima + Sorcerer",
//     tier: "B",
//     speed: "(Late Game Comp)",
//     date: "July 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       {
//         name: "Teemo",
//         item: [],
//       },
//       {
//         name: "Swain",
//         item: [],
//       },
//       { name: "Garen", item: [] },
//       { name: "Lux", item: [] },
//       {
//         name: "Azir",
//         item: ["Guardbreaker", "StatikkShiv", "JeweledGauntlet"],
//       },
//       { name: "Jarvan", item: [] },
//       { name: "Nasus", item: ["Redemption", "SunfireCape", "WarmogsArmor"] },
//       { name: "KSante", item: [] },
//     ],
//   },
//   {
//     name: "6 Shurima",
//     tier: "B",
//     speed: "(Mid Game Comp)",
//     date: "July 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       {
//         name: "Renekton",
//         item: [],
//       },
//       {
//         name: "Cassiopeia",
//         item: [],
//       },
//       { name: "Taliyah", item: [] },
//       { name: "Akshan", item: [] },
//       {
//         name: "Azir",
//         item: ["GuinsoosRageblade", "StatikkShiv", "JeweledGauntlet"],
//       },
//       { name: "Jarvan", item: [] },
//       { name: "Nasus", item: ["Redemption", "SunfireCape", "WarmogsArmor"] },
//       { name: "KSante", item: [] },
//     ],
//   },
//   {
//     name: "6 Sorcerers",
//     tier: "A",
//     speed: "(Mid Game Comp)",
//     date: "July 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       {
//         name: "Malzahar",
//         item: [],
//       },
//       { name: "Sona", item: [] },
//       { name: "Swain", item: [] },
//       { name: "Taric", item: ["Redemption", "IonicSpark", "WarmogsArmor"] },
//       { name: "Velkoz", item: [] },
//       { name: "Jarvan", item: [] },
//       { name: "Lux", item: ["JeweledGauntlet", "BlueBuff", "GiantSlayer"] },
//       { name: "Ahri", item: [] },
//     ],
//   },
//   {
//     name: "8 Sorcerers",
//     tier: "A",
//     speed: "(Mid Game Comp)",
//     date: "July 1st, 2023",
//     augments: [],
//     win: 0,
//     loss: 0,
//     champions: [
//       {
//         name: "Malzahar",
//         item: [],
//       },
//       { name: "Orianna", item: [] },
//       { name: "Swain", item: [] },
//       { name: "Taric", item: [] },
//       { name: "Velkoz", item: [] },
//       { name: "Jarvan", item: ["SorcererEmblem", "WarmogsArmor"] },
//       {
//         name: "Lux",
//         item: ["JeweledGauntlet", "ArchangelsStaff", "HextechGunblade"],
//       },
//       { name: "Ahri", item: ["JeweledGauntlet", "BlueBuff"] },
//     ],
//   },
//   {
//     name: "Garen Reroll",
//     tier: "A",
//     speed: "(Mid Game Comp)",
//     date: "June 15th, 2023",
//     augments: [],
//     win: 2,
//     loss: 0,
//     champions: [
//       { name: "Warwick", item: [] },
//       { name: "Sett", item: [] },
//       { name: "Sona", item: [] },
//       { name: "Garen", item: ["GuinsoosRageblade", "Bloodthirster"] },
//       { name: "Darius", item: ["ZekesHerald", "ZekesHerald", "ZekesHerald"] },
//       { name: "Jarvan", item: ["ZekesHerald", "ZekesHerald", "ZekesHerald"] },
//       { name: "Nasus", item: [] },
//       { name: "Aatrox", item: [] },
//     ],
//   },
//   {
//     name: "6 Noxus",
//     tier: "S",
//     speed: "(Mid Game Comp)",
//     date: "June 15th, 2023",
//     augments: [],
//     win: 2,
//     loss: 0,
//     champions: [
//       {
//         name: "Cassiopeia",
//         item: [],
//       },
//       { name: "Swain", item: [] },
//       { name: "Kled", item: [] },
//       { name: "Ekko", item: [] },
//       {
//         name: "Katarina",
//         item: ["JeweledGauntlet", "IonicSpark", "HandofJustice"],
//       },
//       {
//         name: "Darius",
//         item: ["InfinityEdge", "Bloodthirster", "TitansResolve"],
//       },
//       { name: "Sion", item: [] },
//       { name: "Aatrox", item: [] },
//     ],
//   },
//   {
//     name: "Noxus + Shurima",
//     tier: "A",
//     speed: "(Mid Game Comp)",
//     date: "June 15th, 2023",
//     augments: [],
//     win: 2,
//     loss: 0,
//     champions: [
//       {
//         name: "Cassiopeia",
//         item: [],
//       },
//       { name: "Swain", item: [] },
//       { name: "Kled", item: [] },
//       {
//         name: "Katarina",
//         item: ["JeweledGauntlet", "IonicSpark", "HandofJustice"],
//       },
//       {
//         name: "Darius",
//         item: ["InfinityEdge", "Bloodthirster", "TitansResolve"],
//       },
//       { name: "Azir", item: [] },
//       { name: "Nasus", item: [] },
//       { name: "Sion", item: [] },
//     ],
//   },
//   {
//     name: "Rogue Slayers",
//     tier: "A",
//     speed: "(Mid Game Comp)",
//     date: "June 15th, 2023",
//     augments: [],
//     win: 2,
//     loss: 0,
//     champions: [
//       { name: "Kayle", item: [] },
//       { name: "Viego", item: [] },
//       { name: "Zed", item: ["InfinityEdge", "Bloodthirster", "TitansResolve"] },
//       { name: "Kled", item: [] },
//       { name: "Ekko", item: [] },
//       {
//         name: "Katarina",
//         item: ["JeweledGauntlet", "HandofJustice", "SlayerEmblem"],
//       },
//       { name: "Gwen", item: [] },
//       { name: "Aatrox", item: [] },
//     ],
//   },
//   {
//     name: "Ekko",
//     tier: "S",
//     speed: "(Mid Game Comp)",
//     date: "June 15th, 2023",
//     augments: [],
//     win: 2,
//     loss: 0,
//     champions: [
//       { name: "Ashe", item: [] },
//       {
//         name: "Lissandra",
//         item: [],
//       },
//       {
//         name: "Ekko",
//         item: ["HandofJustice", "HandofJustice", "JeweledGauntlet"],
//       },
//       {
//         name: "Katarina",
//         item: ["JeweledGauntlet", "IonicSpark", "HandofJustice"],
//       },
//       { name: "Urgot", item: [] },
//       { name: "Sejuani", item: [] },
//       { name: "Sion", item: [] },
//     ],
//   },
// ];
