export const season9Traits = [
  { name: "Shurima", synergies: [3, 5, 7, 9] },
  { name: "Noxus", synergies: [3, 6, 9] },
  { name: "Slayer", synergies: [2, 3, 4, 5, 6] },
  { name: "Bastion", synergies: [2, 4, 6, 8] },
  { name: "Demacia", synergies: [3, 5, 7, 9] },
  { name: "Ionia", synergies: [3, 6, 9] },
  { name: "Gunner", synergies: [2, 4, 6] },
  { name: "Void", synergies: [3, 6, 8] },
  { name: "Yordle", synergies: [3, 5] },
  { name: "Darkin", synergies: [1] },
  { name: "Technogenius", synergies: [1] },
  { name: "Sorcerer", synergies: [2, 4, 6, 8] },
  { name: "Challenger", synergies: [2, 4, 6, 8] },
  { name: "Juggernaut", synergies: [2, 4, 6] },
  { name: "Shadow Isles", synergies: [2, 4, 6] },
  { name: "Wanderer", synergies: [3, 5, 7, 9] },
  { name: "Redeemer", synergies: [3, 5, 7, 9] },
  { name: "Strategist", synergies: [2, 3, 4, 5] },
  { name: "Empress", synergies: [1] },
  { name: "Freljord", synergies: [2, 3, 4] },
  { name: "Multicaster", synergies: [2, 4] },
  { name: "Bruiser", synergies: [2, 4, 6] },
  { name: "Zaun", synergies: [2, 4, 6] },
  { name: "Rogue", synergies: [2, 4] },
  { name: "Targon", synergies: [2, 3, 4] },
  { name: "Invoker", synergies: [2, 4, 6] },
  { name: "Piltover", synergies: [3, 6] },
];

export const season9ChampionList = [
  {
    name: "Aatrox",
    cost: 5,
    myCount: 0,
    enemyCount: 0,
    traits: ["Darkin", "Slayer", "Juggernaut"],
  },
  {
    name: "Ahri",
    cost: 5,
    myCount: 0,
    enemyCount: 0,
    traits: ["Ionia", "Sorcerer"],
  },
  {
    name: "Akshan",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shurima", "Deadeye"],
  },
  {
    name: "Aphelios",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Targon", "Deadeye"],
  },
  {
    name: "Ashe",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Freljord", "Deadeye"],
  },
  {
    name: "Azir",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shurima", "Strategist"],
  },
  {
    name: "BelVeth",
    cost: 5,
    myCount: 0,
    enemyCount: 0,
    traits: ["Void", "Empress"],
  },
  {
    name: "Cassiopeia",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Noxus", "Shurima", "Invoker"],
  },
  {
    name: "ChoGath",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Void", "Bruiser"],
  },
  {
    name: "Darius",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Noxus", "Juggernaut"],
  },
  {
    name: "Ekko",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Zaun", "Piltover", "Rogue"],
  },
  {
    name: "Galio",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Demacia", "Invoker"],
  },
  {
    name: "Garen",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Demacia", "Juggernaut"],
  },
  {
    name: "Gwen",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shadow Isles", "Slayer"],
  },
  {
    name: "Heimerdinger",
    cost: 5,
    myCount: 0,
    enemyCount: 0,
    traits: ["Piltover", "Yordle", "Technogenius"],
  },
  {
    name: "Irelia",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Ionia", "Challenger"],
  },
  {
    name: "JarvanIV",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Demacia", "Strategist"],
  },
  {
    name: "Jayce",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Piltover", "Gunner"],
  },
  {
    name: "Jhin",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Ionia", "Deadeye"],
  },
  {
    name: "Jinx",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Zaun", "Gunner"],
  },
  {
    name: "KaiSa",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Void", "Challenger"],
  },
  {
    name: "Kalista",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shadow Isles", "Challenger"],
  },
  {
    name: "Karma",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Ionia", "Invoker"],
  },
  {
    name: "Kassadin",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Void", "Bastion"],
  },
  {
    name: "Katarina",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Noxus", "Rogue"],
  },
  {
    name: "Kayle",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Demacia", "Slayer"],
  },
  {
    name: "Kled",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Noxus", "Yordle", "Slayer"],
  },
  {
    name: "KSante",
    cost: 5,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shurima", "Bastion"],
  },
  {
    name: "Lissandra",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Freljord", "Invoker"],
  },
  {
    name: "Lux",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Demacia", "Sorcerer"],
  },
  {
    name: "Malzahar",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Void", "Sorcerer"],
  },
  {
    name: "Maokai",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shadow Isles", "Bastion"],
  },
  {
    name: "Nasus",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shurima", "Juggernaut"],
  },
  {
    name: "Orianna",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Piltover", "Sorcerer"],
  },
  {
    name: "Poppy",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Yordle", "Demacia", "Bastion"],
  },
  {
    name: "Renekton",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shurima", "Bruiser"],
  },
  {
    name: "RekSai",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Void", "Bruiser"],
  },
  {
    name: "Ryze",
    cost: 5,
    myCount: 0,
    enemyCount: 0,
    traits: ["Wanderer", "Invoker"],
  },
  {
    name: "Samira",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Noxus", "Challenger"],
  },
  {
    name: "Sejuani",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Freljord", "Bruiser"],
  },
  {
    name: "Senna",
    cost: 5,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shadow Isles", "Gunner", "Redeemer"],
  },
  {
    name: "Sett",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Ionia", "Juggernaut"],
  },
  {
    name: "Shen",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Ionia", "Bastion", "Invoker"],
  },
  {
    name: "Sion",
    cost: 5,
    myCount: 0,
    enemyCount: 0,
    traits: ["Noxus", "Bruiser"],
  },
  {
    name: "Sona",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Demacia", "Multicaster"],
  },
  {
    name: "Soraka",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Targon", "Invoker"],
  },
  {
    name: "Swain",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Noxus", "Strategist", "Sorcerer"],
  },
  {
    name: "Taliyah",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shurima", "Multicaster"],
  },
  {
    name: "Taric",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Targon", "Bastion", "Sorcerer"],
  },
  {
    name: "Teemo",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Yordle", "Strategist", "Multicaster"],
  },
  {
    name: "Tristana",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Yordle", "Gunner"],
  },
  {
    name: "Urgot",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Zaun", "Deadeye"],
  },
  {
    name: "VelKoz",
    cost: 3,
    myCount: 0,
    enemyCount: 0,
    traits: ["Void", "Multicaster", "Sorcerer"],
  },
  {
    name: "Vi",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Piltover", "Bruiser"],
  },
  {
    name: "Viego",
    cost: 1,
    myCount: 0,
    enemyCount: 0,
    traits: ["Shadow Isles", "Rogue"],
  },
  {
    name: "Warwick",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Zaun", "Juggernaut", "Challenger"],
  },
  {
    name: "Yasuo",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Ionia", "Challenger"],
  },
  {
    name: "Zed",
    cost: 2,
    myCount: 0,
    enemyCount: 0,
    traits: ["Ionia", "Rogue", "Slayer"],
  },
  {
    name: "Zeri",
    cost: 4,
    myCount: 0,
    enemyCount: 0,
    traits: ["Zaun", "Gunner"],
  },
];

export interface TFTLegendMap {
  [key: number]: string;
}

export const TFTLegendMap: TFTLegendMap = {
  27: "AurelionSol",
  28: "Bard",
  23: "Caitlyn",
  19: "Draven",
  18: "Ezreal",
  26: "LeeSin",
  25: "MasterYi",
  22: "Ornn",
  24: "Pengu",
  16: "TahmKench",
  20: "TwistedFate",
  21: "Urf",
  15: "Veigar",
  17: "Vladimir",
};

export const extraUnitList = [
  "TFT9_NoxianFlag",
  "TFT_TrainingDummy",
  "TFT9_THex",
  "TFT9_VoidEggHerald",
  "TFT9_VoidEggRemora",
  "TFT9_VoidEggBaron",
  "TFT9_HeimerdingerTurret",
];
