import { Season9TeamComp } from "./type";

export const season9ChampionList = [
  "Aatrox",
  "Ahri",
  "Akshan",
  "Aphelios",
  "Ashe",
  "Azir",
  "Belveth",
  "Cassiopeia",
  "Chogath",
  "Darius",
  "Ekko",
  "Galio",
  "Garen",
  "Gwen",
  "Heimerdinger",
  "Irelia",
  "Jarvan",
  "Jayce",
  "Jhin",
  "Jinx",
  "Kaisa",
  "Kalista",
  "Karma",
  "Kassadin",
  "Katarina",
  "Kayle",
  "Kled",
  "Ksante",
  "Lissandra",
  "Lux",
  "Malzahar",
  "Maokai",
  "Nasus",
  "Poppy",
  "Renekton",
  "Reksai",
  "Ryze",
  "Samira",
  "Sejuani",
  "Senna",
  "Sett",
  "Shen",
  "Sion",
  "Sona",
  "Soraka",
  "Swain",
  "Taliyah",
  "Taric",
  "Teemo",
  "Tristana",
  "Urgot",
  "Velkoz",
  "Viego",
  "Vi",
  "Warwick",
  "Yasuo",
  "Zed",
  "Zeri",
];

export const season9TeamCompData: Season9TeamComp[] = [
  {
    name: "Challengers",
    tier: "S",
    speed: "Mid",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Irelia", item: [], imageUrl: "/public/champions/Irelia.png" },
      { name: "Samira", item: [], imageUrl: "/public/champions/Samira.png" },
      { name: "Warwick", item: [], imageUrl: "/public/champions/Warwick.png" },
      { name: "Kalista", item: [], imageUrl: "/public/champions/Kalista.png" },
      { name: "Kaisa", item: [], imageUrl: "/public/champions/Kaisa.png" },
      { name: "Shen", item: [], imageUrl: "/public/champions/Shen.png" },
      { name: "Yasuo", item: [], imageUrl: "/public/champions/Yasuo.png" },
      { name: "Aatrox", item: [], imageUrl: "/public/champions/Aatrox.png" },
    ],
  },
  {
    name: "Void",
    tier: "S",
    speed: "Late",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Chogath", item: [], imageUrl: "/public/champions/Chogath.png" },
      {
        name: "Malzahar",
        item: [],
        imageUrl: "/public/champions/Malzahar.png",
      },
      {
        name: "Kassadin",
        item: [],
        imageUrl: "/public/champions/Kassadin.png",
      },
      { name: "Reksai", item: [], imageUrl: "/public/champions/Reksai.png" },
      { name: "Velkoz", item: [], imageUrl: "/public/champions/Velkoz.png" },
      { name: "Kaisa", item: [], imageUrl: "/public/champions/Kaisa.png" },
      { name: "Yasuo", item: [], imageUrl: "/public/champions/Yasuo.png" },
      { name: "Belveth", item: [], imageUrl: "/public/champions/Belveth.png" },
    ],
  },
  {
    name: "Ionia",
    tier: "A",
    speed: "Late",
    position: "jpg location",
    win: 1,
    loss: 1,
    champions: [
      { name: "Jhin", item: [], imageUrl: "/public/champions/Jhin.png" },
      { name: "Irelia", item: [], imageUrl: "/public/champions/Irelia.png" },
      { name: "Sett", item: [], imageUrl: "/public/champions/Sett.png" },
      { name: "Taric", item: [], imageUrl: "/public/champions/Taric.png" },
      {
        name: "Aphelios",
        item: ["Guinsoo", "LastWhisper"],
        imageUrl: "/public/champions/Aphelios.png",
      },
      { name: "Shen", item: [], imageUrl: "/public/champions/Shen.png" },
      {
        name: "Yasuo",
        item: ["BloodThirster", "EdgeOfNight", "Titan"],
        imageUrl: "/public/champions/Yasuo.png",
      },
      {
        name: "Ahri",
        item: ["BlueBuff", "ArchAngel"],
        imageUrl: "/public/champions/Ahri.png",
      },
    ],
  },
  {
    name: "Ionia 2",
    tier: "A",
    speed: "Late",
    position: "jpg location",
    win: 1,
    loss: 1,
    champions: [
      { name: "Irelia", item: [], imageUrl: "/public/champions/Irelia.png" },
      { name: "Sett", item: [], imageUrl: "/public/champions/Sett.png" },
      { name: "Karma", item: [], imageUrl: "/public/champions/Karma.png" },
      {
        name: "Shen",
        item: [],
        imageUrl: "/public/champions/Shen.png",
      },
      {
        name: "Yasuo",
        item: ["Bloodthirster", "TitansResolve", "GiantSlayer"],
        imageUrl: "/public/champions/Yasuo.png",
      },
      {
        name: "Aatrox",
        item: [],
        imageUrl: "/public/champions/Aatrox.png",
      },
      {
        name: "Ahri",
        item: [],
        imageUrl: "/public/champions/Ahri.png",
      },
      {
        name: "Ksante",
        item: [],
        imageUrl: "/public/champions/Ksante.png",
      },
    ],
  },
  {
    name: "Invokers",
    tier: "B",
    speed: "Mid",
    position: "jpg location",
    win: 2,
    loss: 2,
    champions: [
      { name: "Galio", item: [], imageUrl: "/public/champions/Galio.png" },
      { name: "Soraka", item: [], imageUrl: "/public/champions/Soraka.png" },
      {
        name: "Lissandra",
        item: [],
        imageUrl: "/public/champions/Lissandra.png",
      },
      { name: "Taric", item: [], imageUrl: "/public/champions/Taric.png" },
      { name: "Karma", item: [], imageUrl: "/public/champions/Karma.png" },
      { name: "Shen", item: [], imageUrl: "/public/champions/Shen.png" },
      { name: "Ryze", item: [], imageUrl: "/public/champions/Ryze.png" },
      { name: "Ahri", item: [], imageUrl: "/public/champions/Ahri.png" },
    ],
  },
  {
    name: "DeadEye",
    tier: "S",
    speed: "Late",
    position: "jpg location",
    win: 2,
    loss: 0,
    champions: [
      { name: "Ashe", item: [], imageUrl: "/public/champions/Ashe.png" },
      { name: "Akshan", item: [], imageUrl: "/public/champions/Akshan.png" },
      {
        name: "Lissandra",
        item: [],
        imageUrl: "/public/champions/Lissandra.png",
      },
      { name: "Taric", item: [], imageUrl: "/public/champions/Taric.png" },
      { name: "Sejuani", item: [], imageUrl: "/public/champions/Sejuani.png" },
      { name: "Shen", item: [], imageUrl: "/public/champions/Shen.png" },
      {
        name: "Aphelios",
        item: [],
        imageUrl: "/public/champions/Aphelios.png",
      },
      { name: "Urgot", item: [], imageUrl: "/public/champions/Urgot.png" },
    ],
  },
  {
    name: "Zeri",
    tier: "S",
    speed: "Late",
    position: "jpg location",
    win: 0,
    loss: 2,
    champions: [
      { name: "Jinx", item: [], imageUrl: "/public/champions/Jinx.png" },
      { name: "Jayce", item: [], imageUrl: "/public/champions/Jayce.png" },
      {
        name: "Lissandra",
        item: [],
        imageUrl: "/public/champions/Lissandra.png",
      },
      { name: "Zeri", item: [], imageUrl: "/public/champions/Zeri.png" },
      { name: "Sejuani", item: [], imageUrl: "/public/champions/Sejuani.png" },
      { name: "Shen", item: [], imageUrl: "/public/champions/Shen.png" },
      { name: "Senna", item: [], imageUrl: "/public/champions/Senna.png" },
      { name: "Sion", item: [], imageUrl: "/public/champions/Sion.png" },
    ],
  },
  {
    name: "Yordle Gunner",
    tier: "S",
    speed: "Early",
    position: "jpg location",
    win: 3,
    loss: 0,
    champions: [
      { name: "Poppy", item: [], imageUrl: "/public/champions/Poppy.png" },
      {
        name: "Tristana",
        item: [],
        imageUrl: "/public/champions/Tristana.png",
      },
      { name: "Maokai", item: [], imageUrl: "/public/champions/Maokai.png" },
      { name: "Viego", item: [], imageUrl: "/public/champions/Viego.png" },
      { name: "Jinx", item: [], imageUrl: "/public/champions/Jinx.png" },
      { name: "Jayce", item: [], imageUrl: "/public/champions/Jayce.png" },
      { name: "Zeri", item: [], imageUrl: "/public/champions/Zeri.png" },
      {
        name: "Heimerdinger",
        item: [],
        imageUrl: "/public/champions/Heimerdinger.png",
      },
    ],
  },
  {
    name: "Yordle",
    tier: "A",
    speed: "Early",
    position: "jpg location",
    win: 2,
    loss: 0,
    champions: [
      { name: "Poppy", item: [], imageUrl: "/public/champions/Poppy.png" },
      {
        name: "Tristana",
        item: [],
        imageUrl: "/public/champions/Tristana.png",
      },
      { name: "Kled", item: [], imageUrl: "/public/champions/Kled.png" },
      { name: "Teemo", item: [], imageUrl: "/public/champions/Teemo.png" },
      { name: "Sona", item: [], imageUrl: "/public/champions/Sona.png" },
      { name: "Jarvan", item: [], imageUrl: "/public/champions/Jarvan.png" },
      { name: "Shen", item: [], imageUrl: "/public/champions/Shen.png" },
      {
        name: "Heimerdinger",
        item: [],
        imageUrl: "/public/champions/Heimerdinger.png",
      },
    ],
  },
  {
    name: "Shadow Isle",
    tier: "A",
    speed: "Early",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Maokai", item: [], imageUrl: "/public/champions/Maokai.png" },
      { name: "Viego", item: [], imageUrl: "/public/champions/Viego.png" },
      { name: "Zed", item: [], imageUrl: "/public/champions/Zed.png" },
      { name: "Ekko", item: [], imageUrl: "/public/champions/Ekko.png" },
      { name: "Kalista", item: [], imageUrl: "/public/champions/Kalista.png" },
      {
        name: "Katarina",
        item: [],
        imageUrl: "/public/champions/Katarina.png",
      },
      { name: "Gwen", item: [], imageUrl: "/public/champions/Gwen.png" },
    ],
  },
  {
    name: "Shadow Isle 2",
    tier: "A",
    speed: "Late",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Maokai", item: [], imageUrl: "/public/champions/Maokai.png" },
      { name: "Viego", item: [], imageUrl: "/public/champions/Viego.png" },
      { name: "Zed", item: [], imageUrl: "/public/champions/Zed.png" },
      { name: "Kled", item: [], imageUrl: "/public/champions/Kled.png" },
      { name: "Gwen", item: [], imageUrl: "/public/champions/Gwen.png" },
      {
        name: "Aatrox",
        item: [],
        imageUrl: "/public/champions/Aatrox.png",
      },
      { name: "Ksante", item: [], imageUrl: "/public/champions/Ksante.png" },
      { name: "Senna", item: [], imageUrl: "/public/champions/Senna.png" },
    ],
  },
  {
    name: "Multicaster",
    tier: "S",
    speed: "Mid",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Taliyah", item: [], imageUrl: "/public/champions/Taliyah.png" },
      { name: "Teemo", item: [], imageUrl: "/public/champions/Teemo.png" },
      { name: "Swain", item: [], imageUrl: "/public/champions/Swain.png" },
      { name: "Galio", item: [], imageUrl: "/public/champions/Galio.png" },
      { name: "Velkoz", item: [], imageUrl: "/public/champions/Velkoz.png" },
      { name: "Sona", item: [], imageUrl: "/public/champions/Sona.png" },
      { name: "Jarvan", item: [], imageUrl: "/public/champions/Jarvan.png" },
      { name: "Shen", item: [], imageUrl: "/public/champions/Shen.png" },
    ],
  },
  {
    name: "Strategist",
    tier: "B",
    speed: "Mid",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Taliyah", item: [], imageUrl: "/public/champions/Taliyah.png" },
      { name: "Teemo", item: [], imageUrl: "/public/champions/Teemo.png" },
      { name: "Swain", item: [], imageUrl: "/public/champions/Swain.png" },
      { name: "Garen", item: [], imageUrl: "/public/champions/Garen.png" },
      { name: "Azir", item: [], imageUrl: "/public/champions/Azir.png" },
      { name: "Jarvan", item: [], imageUrl: "/public/champions/Jarvan.png" },
      { name: "Nasus", item: [], imageUrl: "/public/champions/Nasus.png" },
      { name: "Lux", item: [], imageUrl: "/public/champions/Lux.png" },
    ],
  },
  {
    name: "Shurima",
    tier: "B",
    speed: "Mid",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      {
        name: "Renekton",
        item: [],
        imageUrl: "/public/champions/Renekton.png",
      },
      {
        name: "Cassiopeia",
        item: [],
        imageUrl: "/public/champions/Cassiopeia.png",
      },
      { name: "Taliyah", item: [], imageUrl: "/public/champions/Taliyah.png" },
      { name: "Akshan", item: [], imageUrl: "/public/champions/Akshan.png" },
      { name: "Azir", item: [], imageUrl: "/public/champions/Azir.png" },
      { name: "Jarvan", item: [], imageUrl: "/public/champions/Jarvan.png" },
      { name: "Nasus", item: [], imageUrl: "/public/champions/Nasus.png" },
      { name: "Ksante", item: [], imageUrl: "/public/champions/Ksante.png" },
    ],
  },
  {
    name: "Sorcerers",
    tier: "A",
    speed: "Mid",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      {
        name: "Malzahar",
        item: [],
        imageUrl: "/public/champions/Malzahar.png",
      },
      { name: "Sona", item: [], imageUrl: "/public/champions/Sona.png" },
      { name: "Swain", item: [], imageUrl: "/public/champions/Swain.png" },
      { name: "Taric", item: [], imageUrl: "/public/champions/Taric.png" },
      { name: "Velkoz", item: [], imageUrl: "/public/champions/Velkoz.png" },
      { name: "Jarvan", item: [], imageUrl: "/public/champions/Jarvan.png" },
      { name: "Lux", item: [], imageUrl: "/public/champions/Lux.png" },
      { name: "Ahri", item: [], imageUrl: "/public/champions/Ahri.png" },
    ],
  },
  {
    name: "Garen",
    tier: "A",
    speed: "Mid",
    position: "jpg location",
    win: 2,
    loss: 0,
    champions: [
      { name: "Warwick", item: [], imageUrl: "/public/champions/Warwick.png" },
      { name: "Sett", item: [], imageUrl: "/public/champions/Sett.png" },
      { name: "Sona", item: [], imageUrl: "/public/champions/Sona.png" },
      { name: "Garen", item: [], imageUrl: "/public/champions/Garen.png" },
      { name: "Darius", item: [], imageUrl: "/public/champions/Darius.png" },
      { name: "Jarvan", item: [], imageUrl: "/public/champions/Jarvan.png" },
      { name: "Nasus", item: [], imageUrl: "/public/champions/Nasus.png" },
      { name: "Aatrox", item: [], imageUrl: "/public/champions/Aatrox.png" },
    ],
  },
  {
    name: "Noxus 1",
    tier: "S",
    speed: "Mid",
    position: "jpg location",
    win: 2,
    loss: 0,
    champions: [
      {
        name: "Cassiopeia",
        item: [],
        imageUrl: "/public/champions/Cassiopeia.png",
      },
      { name: "Swain", item: [], imageUrl: "/public/champions/Swain.png" },
      { name: "Kled", item: [], imageUrl: "/public/champions/Kled.png" },
      { name: "Ekko", item: [], imageUrl: "/public/champions/Ekko.png" },
      {
        name: "Katarina",
        item: [],
        imageUrl: "/public/champions/Katarina.png",
      },
      { name: "Darius", item: [], imageUrl: "/public/champions/Darius.png" },
      { name: "Sion", item: [], imageUrl: "/public/champions/Sion.png" },
      { name: "Aatrox", item: [], imageUrl: "/public/champions/Aatrox.png" },
    ],
  },
  {
    name: "Noxus 2",
    tier: "A",
    speed: "Mid",
    position: "jpg location",
    win: 2,
    loss: 0,
    champions: [
      {
        name: "Samira",
        item: [],
        imageUrl: "/public/champions/Samira.png",
      },
      { name: "Swain", item: [], imageUrl: "/public/champions/Swain.png" },
      { name: "Kled", item: [], imageUrl: "/public/champions/Kled.png" },
      { name: "Zed", item: [], imageUrl: "/public/champions/Zed.png" },
      {
        name: "Katarina",
        item: [],
        imageUrl: "/public/champions/Katarina.png",
      },
      { name: "Darius", item: [], imageUrl: "/public/champions/Darius.png" },
      { name: "Sion", item: [], imageUrl: "/public/champions/Sion.png" },
      { name: "Aatrox", item: [], imageUrl: "/public/champions/Aatrox.png" },
    ],
  },
  {
    name: "Rogue",
    tier: "A",
    speed: "Early",
    position: "jpg location",
    win: 2,
    loss: 0,
    champions: [
      { name: "Viego", item: [], imageUrl: "/public/champions/Viego.png" },
      { name: "Warwick", item: [], imageUrl: "/public/champions/Warwick.png" },
      { name: "Zed", item: [], imageUrl: "/public/champions/Zed.png" },
      { name: "Kled", item: [], imageUrl: "/public/champions/Kled.png" },
      { name: "Ekko", item: [], imageUrl: "/public/champions/Ekko.png" },
      {
        name: "Katarina",
        item: [],
        imageUrl: "/public/champions/Katarina.png",
      },
      { name: "Darius", item: [], imageUrl: "/public/champions/Darius.png" },
    ],
  },
  {
    name: "Ekko",
    tier: "S",
    speed: "Mid",
    position: "jpg location",
    win: 2,
    loss: 0,
    champions: [
      { name: "Viego", item: [], imageUrl: "/public/champions/Viego.png" },
      { name: "Ashe", item: [], imageUrl: "/public/champions/Ashe.png" },
      { name: "Zed", item: [], imageUrl: "/public/champions/Zed.png" },
      { name: "Warwick", item: [], imageUrl: "/public/champions/Warwick.png" },
      { name: "Ekko", item: [], imageUrl: "/public/champions/Ekko.png" },
      {
        name: "Katarina",
        item: [],
        imageUrl: "/public/champions/Katarina.png",
      },
      { name: "Sejuani", item: [], imageUrl: "/public/champions/Sejuani.png" },
      { name: "Sion", item: [], imageUrl: "/public/champions/Sion.png" },
    ],
  },
];
