import { Season9TeamComp } from "./type";

export const season9ChampionList = [
  "Aatrox",
  "Ahri",
  "Akshan",
  "Aphelios",
  "Ashe",
  "Azir",
  "Belveth",
  "Cassiopeia",
  "Chogath",
  "Darius",
  "Ekko",
  "Galio",
  "Garen",
  "Gwen",
  "Heimerdinger",
  "Irelia",
  "Jarvan",
  "Jayce",
  "Jhin",
  "Jinx",
  "Kaisa",
  "Kalista",
  "Karma",
  "Kassadin",
  "Katarina",
  "Kayle",
  "Kled",
  "Ksante",
  "Lissandra",
  "Lux",
  "Malzahar",
  "Maokai",
  "Nasus",
  "Poppy",
  "Renekton",
  "Reksai",
  "Ryze",
  "Samira",
  "Sejuani",
  "Senna",
  "Sett",
  "Shen",
  "Sion",
  "Sona",
  "Soraka",
  "Swain",
  "Taliyah",
  "Taric",
  "Teemo",
  "Tristana",
  "Urgot",
  "Velkoz",
  "Viego",
  "Vi",
  "Warwick",
  "Yasuo",
  "Zed",
  "Zeri",
];

export const season9TeamCompData: Season9TeamComp[] = [
  {
    name: "Challengers",
    tier: "S",
    speed: "Mid",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Irelia", item: [] },
      { name: "Samira", item: [] },
      { name: "Warwick", item: [] },
      { name: "Kalista", item: [] },
      { name: "Kaisa", item: [] },
      { name: "Yasuo", item: [] },
      { name: "Shen", item: [] },
      { name: "Aatrox", item: [] },
    ],
  },
  {
    name: "Void",
    tier: "S",
    speed: "Late",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Chogath", item: [] },
      { name: "Malzahar", item: [] },
      { name: "Kassadin", item: [] },
      { name: "Reksai", item: [] },
      { name: "Kaisa", item: [] },
      { name: "Yasuo", item: [] },
      { name: "Velkoz", item: [] },
      { name: "Belveth", item: [] },
    ],
  },
  {
    name: "Ionia",
    tier: "S",
    speed: "Late",
    position: "jpg location",
    win: 0,
    loss: 0,
    champions: [
      { name: "Chogath", item: [] },
      { name: "Malzahar", item: [] },
      { name: "Kassadin", item: [] },
      { name: "Reksai", item: [] },
      { name: "Kaisa", item: [] },
      { name: "Yasuo", item: [] },
      { name: "Velkoz", item: [] },
      { name: "Belveth", item: [] },
    ],
  },
];
